# Taller Fundamentos de Python

## Python Notebooks
Los notebooks de Python proveen un ambiente interactivo para experimentación de código, visualización y publicación de resultados.

Las casillas de color gris claro que se encuentran a continuación se denominan celdas y estas pueden contener código (code) o texto formateado (Markdown).

* [Flechas arriba / abajo] Mover arriba y abajo de celda a celda.
* [Enter] Ingresa una celda para editarla.
* [Shift + Enter] Evalúa una celda, muestra el resultado y pasa a la siguiente celda.
* [Ctrl + Enter] Evalúa una celda, muestra el resultado y permanece en la celda.
* [Alt + Enter] Evalúa una celda, muestra el resultado e inserta una celda abajo.
* [Esc] - [D] - [D] Eliminar una celda.
* [Esc] - [Z] Deshacer eliminar una celda.
* [Esc] - [B] Insertar una celda debajo de la celda actual.
* [Esc] - [A] Insertar una celda sobre la celda actual.
* [Esc] - [M] Convierte la celda de código en markdown.
* [Esc] - [Y] Convierte la celda de Markdown a código.

Para más atajos de teclado vaya al menú Ayuda -> Atajos de teclado

In [1]:
print("Hola mundo")

Hola mundo


## Variables en Python

**Variable**: Es donde se guarda determinada información (texto, números, booleanas, etc.)

Cada variable tiene un nombre para referirse a ella, Python tiene en cuenta si escribimos en mayúsculas o minúsculas la variable (case sensitive).

Para definir variables en Python se realiza de la siguiente manera:

```python
# Asignando un valor
variable = valor
# Asignando varios valores
variable1, variable2 = valor1, valor2
```

Python al asignar la variable define cual es el tipo de datos más apropiado.  

### Números

En números hay dos tipos principales, los números enteros (int) y los reales (float).  El separador decimal es el punto.

```python
entero = 2
real = 2.5
```

### Texto

Las variables que almacenan texto se denominan strings (str).  Se deben de poner entre commillas sencillas o dobles, si el texto es multilinea con triple comilla.

```python
cadena = "Hola"
cadena = 'Hola'
multilinea = """ Hola
                Mundo """
multilinea = ''' Hola
                Mundo '''             
```

### Listas

Son conjuntos ordenados de elementos (números, texto, listas, etc). Se delimitan por corchetes (`[]`) y los elementos se separan por comas. Las listas son dinamicas, es decir que son mutables.

```python
listaNumeros = [1,2,3]
listaCadenas = ['a','b','c']
listaListas = [[1,2],[3,4],[5,6]]
listaMixtas = [1,'Grupo',[1,2,3,4]]
listaVacia = []
```

### Tuplas

Es un conjunto ordenado e inmutable de elementos del mismo o diferente tipo. Las tuplas se representan escribiendo los elementos entre paréntesis (`()`) y separados por comas. Las tuplas son estaticas, son inmutables, una vez creada no puede ser modificada.

```python
tuplaNumeros = (1,2,3)
tuplaCadenas = ('a','b','c')
tuplaListas = ([1,2],[3,4],[5,6])
tuplaMixtas = (1,'Grupo',[1,2,3,4])
```

### Diccionarios

Permite almacenar cualquier tipo de valor como enteros, cadenas, listas, etc.  Los diccionarios permiten además identificar cada elemento por una clave (key)

```python
dictNumeros = {'k1':1,'k2':2}
dictCadenas = {'k1':'a','k2':'b','k3':'c'}
dictListas = {'k1':[1,2],'k2':[3,4],'k3':[5,6]}
dictMixto = {'k1':1,'k2':'Grupo','k3':[1,2,3,4]}
```

### Booleano

Una variable booleana es una variable que sólo puede tomar dos posibles valores: Verdadero (True) o Falso (False).

```python
verdadero = True
falso = False
```

### None

Es el tipo de dato que en otros lenguajes se conoce como Nulo (NAN).  En Python es NoneType.

```python
nulo = None
```

### Imprimir variables

El comando `print(variable)` imprime el valor de la variable.


### Comentarios

Los comentarios en linea se define con `#`

## Operadores Aritméticos

| Symbol | Task Performed |
|----|---|
| +  | Addition |
| -  | Subtraction |
| /  | division |
| %  | mod |
| *  | multiplication |
| //  | floor division |
| **  | exponentiation |
| ~   | negation |

Python dependiendo del tipo de dato realiza las operaciones.

In [106]:
x = 5
y = 7

print('suma: ',x+y)
z = x*5+y
print('funcion: ',z)

print('operacion exponencial: ',x**y)
print('operacion division:',x/y)

print('operacion multiplicacion: ',x*y)

print('operacion modulo: ',x%y)

# Valor absoluto de un numero
print('Valor absoluto: ', abs(-45))

suma:  12
funcion:  32
operacion exponencial:  78125
operacion division: 0.7142857142857143
operacion multiplicacion:  35
operacion modulo:  5
Valor absoluto:  45


## Variables en python:

In [4]:
mensaje = 'Estamos aprendiendo Python'
n = 2021
pi = 3.1415926535897931


Este ejemplo hace tres asignaciones. La primera asigna una cadena a una variable nueva llamada mensaje; la segunda asigna el entero 2021 a n; la tercera asigna el valor (aproximado) de π a pi. Para mostrar el valor de una variable, se puede usar la sentencia print:

In [13]:
print('esto es un string: ',mensaje)
print('es un entero: ',n)
print('es un float: ',pi)



esto es un string:  Estamos aprendiendo Python
es un entero:  2021
es un float:  3.141592653589793


## operaciones con cadenas

In [6]:
x = "bit "
y = 3
print(x*y)

bit bit bit 


In [7]:
X = "Bogota"
Y = " es una ciudad de Colombia"

print(X+Y)

Bogota es una ciudad de Colombia


In [14]:
# Declarando una lista
listaNumeros = [1,2,3]
print(listaNumeros)
listaCadenas = ['a','b','c']
print(listaCadenas)
listaListas = [[1,2],[3,4],[5,6]]
print(listaListas)
listaMixtas = [1,'Grupo',[1,2,3,4]]
print(listaMixtas)
listaVacia = []
print(listaVacia)

[1, 2, 3]
['a', 'b', 'c']
[[1, 2], [3, 4], [5, 6]]
[1, 'Grupo', [1, 2, 3, 4]]
[]


In [15]:
# Declarando una Tupla
tuplaNumeros = (1,2,3)
print(tuplaNumeros)
tuplaCadenas = ('a','b','c')
print(tuplaCadenas)
tuplaListas = ([1,2],[3,4],[5,6])
print(tuplaListas)
tuplaMixtas = (1,'Grupo',[1,2,3,4])
print(tuplaMixtas)

(1, 2, 3)
('a', 'b', 'c')
([1, 2], [3, 4], [5, 6])
(1, 'Grupo', [1, 2, 3, 4])


In [16]:
# Declarando Diccionarios
dictNumeros = {'k1':1,'k2':2}
print(dictNumeros)
dictCadenas = {'k1':'a','k2':'b','k3':'c'}
print(dictCadenas)
dictListas = {'k1':[1,2],'k2':[3,4],'k3':[5,6]}
print(dictListas)
dictMixto = {'k1':1,'k2':'Grupo','k3':[1,2,3,4]}
print(dictMixto)

{'k1': 1, 'k2': 2}
{'k1': 'a', 'k2': 'b', 'k3': 'c'}
{'k1': [1, 2], 'k2': [3, 4], 'k3': [5, 6]}
{'k1': 1, 'k2': 'Grupo', 'k3': [1, 2, 3, 4]}


In [ ]:
# Declarando Booleanos
verdadero = True
falso = False

# Declarando Nulos
nulo = None

Los programadores generalmente eligen nombres para sus variables que tengan sentido y documentan para qué se usa esa variable. Los nombres de las variables pueden ser arbitrariamente largos. Pueden contener tanto letras como números, pero no pueden comenzar con un número. Se pueden usar letras mayúsculas, pero es buena idea comenzar los nombres de las variables con una letras minúscula.

In [18]:
# Asignaciones Múltiples
var1, var2, var3 =  ( 5 + 4),  "Sara", [13, 17, 23]
print( "var1 =", var1 )
print( "var2 =", var2 )
print( "var3 =", var3 )

# Cambiar valores entre variables
var1, var2 = var2, var1 

print( "var1 =", var1 )
print( "var2 =", var2 )

var1 = 9
var2 = Sara
var3 = [13, 17, 23]
var1 = Sara
var2 = 9


## Tipo de Datos

Para conocer el tipo de dato de una variable se usa el metodo type

type(x)

In [19]:
print(x)
type(x)

10


int

## Operadores Relacionales

| Symbol | Task Performed |
|----|---|
| == | verdadero, si los valores son iguales |
| is | verdadero, si son identicos, i.e. el **mismo** objeto  |
| !=  | Verdadero, si no son iguales |
| < | Menos que |
| > | Mas que|
| <=  | Menor o igual que |
| >=  | Mayor o igual que |
| in  | Evalua pertenencia a una coleccion (list, set, dictionary) |

In [29]:
print(x == 2)
print(x != 2)
print(x > 1)
print(listaNumeros)
print(listaNumeros == [1,2,3])
print(listaNumeros is [1,2,3])
objecto = listaNumeros
listaNumeros is objecto
nulo = None
print(nulo is None)

False
True
True
[1, 2, 3]
True
False
True


## Conversiones entre tipos

Python cuenta con la conversión de tipos de datos (*cast* o *casting*) que especifica explicitamente el tipo de dato.

```python
int(variable)
float(variable)
str(variable)
bool(variable)
list(variable)
tuple(variable)
dict(variable)
```

In [32]:
# Convertir Lista a tupla
print(listaCadenas)
print(type(listaCadenas))
print(tuple(listaCadenas))
print(type(tuple(listaCadenas)))


# Convertir de cadena a entero
print('123')
print(type('123'))
print(int('123'))
print(type(int('123')))

['a', 'b', 'c']
<class 'list'>
('a', 'b', 'c')
<class 'tuple'>
123
<class 'str'>
123
<class 'int'>




Funciones Integradas (Built-in Functions)
Funciones: Una función es un bloque de código con un nombre asociado, que recibe  
0
  o más argumentos como entrada, sigue una serie de instrucciones y devuelve un valor o realiza una tarea.

Python dispone de una serie de funciones intregradas al lenguaje( built-in)

Un ejemplo de estas funciones son las vistas en los anteriores puntos como las de convertir tipos de datos y la de imprimir.

In [108]:
# Ingresar valor por teclado
entrada = int(input("Ingrese un número entero: "))
print(entrada**2)

4


### Ejercicio 1:


Ejecute la siguiente  celda e infiera lo que hace la función round incorporada con uno o dos argumentos.

In [38]:
print(round( -4.78 ))
print(round( -3.141516297, 4 ))
print(round( -3.141516297, 7 ))

-5
-3.1415
-3.1415163


### Ejercicio 2:


Desde la pagina de las funciones integradas [built-in](https://docs.python.org/3/library/functions.html), consulte la forma de usar la función `min()` y `max()`.

- Cree una lista con los valores 42, 17 y 68.
- Usando la función `min()`, imprima el valor minimo.
- Usando la función `max()`, imprima el valor maximo.
- Validar si hay una función que me devuelva la suma?

### Indexación de Cadenas

Las cadenas de Python son cadenas de caracteres, y cada carácter reside en un índice a partir de $0$ (para el primer carácter) y terminando en longitud de cadena $-1$ (para el último carácter).

|G|r|u|p|o|
|-|-|-|-|-|
|0|1|2|3|4|
|-|-|-|-|-|
|-5|-4|-3|-2|-1|


In [40]:
cadena = "la altura de juan es 4m"
print("Primer caracter: ",cadena[0])
print("Ultimo caracter: ",cadena[-1])

Primer caracter:  l
Ultimo caracter:  m


Si se desea cambiar el valor de un caracter de una cadena se debe de usar las funciones propias del objeto string.

In [41]:
str.replace(cadena,'u','o')


'la altora de joan es 4m'

Si se desea conocer el tamaño de la cadena de caracteres se usa el metodo `len(cadena)`.

In [43]:
len(cadena)

23

Si se desea conocer si un caracter esta en una cadena de caracteres se usa el operador in.

In [44]:
'a' in cadena

True

### Cortar (Slicing) Cadenas

**Slicing** en Python es un camino poderoso para extraer sub-partes de una cadena, listas y tuplas.

```
str[start:end]
````
**start**: sub-cadena inicia desde este elemento

**end**: fin sub-cadena, excluye el elemento en este index.

|G|r|u|p|o|
|-|-|-|-|-|
|0|1|2|3|4|

```python
cadena = "Grupo"
print(cadena[0:2])
```
|G|r|
|-|-|
|0|1|


In [47]:
cadena = "Grupo"
print(cadena[0:2])


# Sub-cadena desde la posicion inicial, 4 caracteres.
print(cadena[0:4])

Gr
Grup


## Manejo de Listas

Una lista es un arreglo de elementos donde podemos ingresar cualquier tipo de dato, para acceder a estos datos lo podemos hacer mediante un índice.

In [49]:
lista = [1,2.5,'Grupo',[1,2],10,'Grupo']

In [50]:
print("Primer elemento de la lista: ",lista[0])
print("Ultimo elemento de la lista: ",lista[-1])

Primer elemento de la lista:  1
Ultimo elemento de la lista:  Grupo


In [51]:
print(lista[3][1])

2


In [52]:
# Adicionar un elemento a la lista
lista.append('Nuevo')
print(lista)

[1, 2.5, 'Grupo', [1, 2], 10, 'Grupo', 'Nuevo']


In [53]:
# Devuelve el número de indice del elemento que le pasamor por parámetro
print(lista.index('Grupo'))

2


In [54]:
# Devuelve el elemento en la posicion dada de la lista y lo elimina
print(lista.pop(2))
print(lista)



Grupo
[1, 2.5, [1, 2], 10, 'Grupo', 'Nuevo']


In [55]:
# Devuelve cuantas veces un elemento de una lista se repite
print(lista.count('Grupo'))

1


In [56]:
# Invertir los elementos de una lista
lista.reverse()
print(lista)

['Nuevo', 'Grupo', 10, [1, 2], 2.5, 1]


## Manejo de Diccionarios

Al contrario de las listas los diccionarios no tienen orden, un diccionario es una palabra que tiene asociado algo.

Se crean poniendo sus elementos entre llaves (`{"a":"Alicante","b":"Barcelona"}`). Se denominan keys a las **palabras** y values a las **definiciones**. Lógicamente no puede haber dos keys iguales, pero si dos values iguales.


In [57]:
diccionario = {'Piloto 1':'Fernando Alonso', 'Piloto 2':'Kimi Raikkonen', 'Piloto 3':'Felipe Massa'}
print(diccionario)

{'Piloto 1': 'Fernando Alonso', 'Piloto 2': 'Kimi Raikkonen', 'Piloto 3': 'Felipe Massa'}


In [58]:
# Devuelve el valor que corresponde con la key introducida.
print(diccionario.get('Piloto 1'))
print(diccionario['Piloto 1'])

Fernando Alonso
Fernando Alonso


In [59]:
# Devuelve el valor que corresponde con la key introducida, y luego borra la key y el valor.
print(diccionario.pop('Piloto 1'))
print(diccionario)

Fernando Alonso
{'Piloto 2': 'Kimi Raikkonen', 'Piloto 3': 'Felipe Massa'}


In [60]:
# Actualiza el valor de una determinada key o lo crea si no existe.
diccionario.update({'Piloto 4':'Lewis Hamilton'})
diccionario.update({'Piloto 2':'Sebastian Vettel'})
print(diccionario)

{'Piloto 2': 'Sebastian Vettel', 'Piloto 3': 'Felipe Massa', 'Piloto 4': 'Lewis Hamilton'}


In [61]:
diccionario['Piloto 5'] = 'Juan Perez'
print(diccionario)

{'Piloto 2': 'Sebastian Vettel', 'Piloto 3': 'Felipe Massa', 'Piloto 4': 'Lewis Hamilton', 'Piloto 5': 'Juan Perez'}


In [62]:
# "key" in diccionario: devuelve verdadero (True) o falso (False) si la key existe en el diccionario.
print ("Piloto 2" in diccionario)
print ("piloto 1" in diccionario)
print ("Sebastian Vettel" in diccionario)

True
False
False


In [63]:
# "definición" in diccionario.values(): devuelve verdadero (True) o falso (False) si la definición existe en el diccionario.
print ("Sebastian Vettel" in diccionario.values())

True


## Manejo de Tuplas

Las tuplas son inmutables, una vez creada, no se puede cambiar ni su contenido ni su tamaño.

In [65]:
tuple1 = (1,2,3,4,5)
tuple2 = (6,7,8,9,10)

# Concatenar tuplas
tuple3 = tuple1 + tuple2
print(tuple3)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [66]:
# Repetir tuplas
print(tuple1 * 3)

(1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5)


In [67]:
# Validar si un elemento esta en la tupla
print(7 in tuple1)
print(7 in tuple2)

False
True


In [68]:
# Devuelve cuantas veces esta un elemento repetido
tuple4 = (65,67,5,67,34,76,67,231,98,67)
print(tuple4.count(67))

4


In [69]:
# Indexación
print(tuple4[4])
print(tuple4[-4])
print(tuple4[:4])
print(tuple4[5:])
print(tuple4[-6:-2])
print(tuple4[3:6])

34
67
(65, 67, 5, 67)
(76, 67, 231, 98, 67)
(34, 76, 67, 231)
(67, 34, 76)


## Funciones de Usuario

Hasta ahora, sólo hemos estado usando las funciones que vienen incorporadas en
Python, pero es posible añadir también funciones nuevas. Una definición de función especifica el nombre de una función nueva y la secuencia de sentencias que se
ejecutan cuando esa función es llamada. Una vez definida una función, se puede
reutilizar una y otra vez a lo largo de todo el programa.


En Python, la definición de funciones se realiza mediante la instruccion `def`.  La definición de la función finaliza con dos puntos (`:`) y el algoritmo que la compone, irá con tabulación.

In [71]:
def suma_numeros(x,y):
    z = x+y
    return z

In [72]:
suma_numeros(10,85)

95

### Ejercicio 3

Escriba una función que calcule el area de un triangulo:

$Area = (Base*Altura)/2 $

$Base$ Es un numero entero o real.
$Altura$ Es un numero entero o real.

La función debe de retornar el valor del $Area$.

# Estructuras de control


## Condicional IF - ELIF - ELSE

In [33]:
print("Aprendamos a utilizar condicionales")
x = 10
if x%2 == 0 :
    print('x es par')
else :
    print('x es impar')


Aprendamos a utilizar condicionales
x es par


In [34]:
x= 10
y =  6

if x < y:
    print('x es menor que y')
elif x > y:
    print('x es mayor que y')
else:
    print('x e y son iguales')


x es mayor que y



## Ciclos FOR

Los ciclos For en Python son simples. La estructura basica esta dada por **`for <var-name> in <iterable> :`**
**Importante** finalizando el for siempre debe de ir **:**, es obligatorio y para los constructores del flujo de control son obligación. 

El bloque que sera iterado esta determinado por la tabulación de las lineas siguientes del for.   
   
La linea en blanco despues de las dos sentencias no es obligatoria, pero es considerada buena practica. Las lineas luego del ciclo for no llevan tabulación, por lo tanto ya estan fuera del ciclo.

In [74]:
string_list = [ "Juan", "is", "1.70", "metres", "high"]

for elem in string_list : 
    print( elem )
    print( len(elem), 'characters\n' )
    
print( "The loop is done")

Juan
4 characters

is
2 characters

1.70
4 characters

metres
6 characters

high
4 characters

The loop is done


In [75]:
for idx in range(len(string_list)):
  print(idx)
  print(string_list[idx])
  print(len(string_list[idx]))

0
Juan
4
1
is
2
2
1.70
4
3
metres
6
4
high
4


#### Otra forma de iterar un ciclo for : range ( a, b, s )

Una forma común de iterar un ciclo for es desde 0 hasta n-1.  Esto se puede implementar con una funcion range.

In [ ]:
n = 10 # desired number of iterations

for  i in range(0,10) : 
    print( f"i = {i}")

## La sentencia while
Los computadores se suelen utilizar a menudo para automatizar tareas repetitivas. Repetir
tareas idénticas o muy similares sin cometer errores es algo que a las máquinas
se les da bien y en cambio a las personas no. Como las iteraciones resultan tan habituales, Python proporciona varias características en su lenguaje para hacerlas
más sencillas.
Una forma de iteración en Python es la sentencia while. He aquí un programa
sencillo que cuenta hacia atrás desde diez y luego dice  '¡Arranque!'

In [76]:
n = 10
while n > 0:
    print(n)
    n = n - 1
print('¡Arranque!')


10
9
8
7
6
5
4
3
2
1
¡Arranque!


### Finalizar iteraciones con continue
Algunas veces, estando dentro de un bucle se necesita terminar con la iteración
actual y saltar a la siguiente de forma inmediata. En ese caso se puede utilizar
la sentencia continue para pasar a la siguiente iteración sin terminar la ejecución
del cuerpo del bucle para la actual.
A continuación se muestra un ejemplo de un bucle que repite lo que recibe como
entrada hasta que el usuario escribe “fin”, pero trata las líneas que empiezan por el
carácter almohadilla como líneas que no deben mostrarse en pantalla (algo parecido
a lo que hace Python con los comentarios).


In [79]:
while True:
    linea = input('> ')
    if linea[0] == '#' :
        continue
    if linea == 'fin':
        break
    print(linea)
print('¡Terminado!')

¡Terminado!


### Ejercicio 4

Dado un número entero $n$, realice las siguientes acciones condicionales:

1. Si es impar imprima 'Extraño'
2. Si es par y esta en el rango inclusive de 2 a 5, imprima 'No Extraño'
3. Si es par y esta en el rango inclusive de 6 a 20, imprima 'Extraño' 
4. Si es par y es más grande que 20, imprima 'No Extraño'

***Ejemplos:***
$$n = 3$$
$n$ es impar y los números impares son de tipo 'Extraño', así que debe de imprimir 'Extraño'.
$$n = 24$$
$n$ es par y es mayor que 20, los números pares mayores que 20 son de tipo ' No Extraño', así que debe de imprimir 'No Extraño'.


## Excepciones

Sin importar que la declaración este sintácticamente correcta, puede generar un error cuando se intenta ejecutarla. Los errores detectados durante la ejecución se llaman excepciones pueden ser manejados por los programas en Python. 

La declaración `try` nos permite manejar las excepciones y trabaja de la siguiente manera:

1. Se ejecuta el *bloque try* (el código entre la declaración `try`y `except`)
2. Si no ocurre una excepción el `boque except` se omite y termina la ejecución de la declaración `try`.
3. Si ocurre una excepción durante la ejecución del *bloque try*, el resto del bloque se omite.  Si el tipo de excepción coincide con la excepción nombreada luevo de la palabra reservada `except`, se ejecuta el *bloque except*, y la ejecución continúa luego de la declaración `try`.
4. Si ocurre una excepción que no coincida con la excepción nombrada en el `except`, esta es una excepción no manejada y la ejecución se frena con un mensaje de error indicando lo que sucedió, por ejemplo: **ZeroDivisionError**, **NameError**, **TypeError** y **ValueError**.

In [84]:
# try-except structure with particular type of exception defined
my_string = "asd"
try : 
    my_string_as_float = 2 / 0 #float( my_string ) 
    print( "the entered value could be converted directly to a number")
except :  
    # capture this particular type of exception and bind it to the name 'err'
    print( "an exception was thrown: defaulting to special float value = nan")
    a_as_float = float( "nan")



an exception was thrown: defaulting to special float value = nan


In [85]:
# try-except structure with general type of exception
my_string = 12
try : 
    my_string_as_float = float( my_string ) 
    print( "the entered value could be converted directly to a number")
except:  
    # capture this particular type of exception and bind it to the name 'err'
    print( "an exception was thrown: defaulting to special float value = nan")
    a_as_float = float( "nan")
    print( f"a_as_float = {a_as_float}")

the entered value could be converted directly to a number


# Clases

Las clases proveen una forma de empaquetar datos y funcionalidad juntos. Al crear una nueva clase, se crea un nuevo *tipo* de objeto, permitiendo crear nuevas *instancias* de este tipo.  Cada instancia de clase puede tener atributos adjuntos para mantener su estado.  Las instancias de clase también pueden tener métodos (definidos por su clase) para modificar su estado.

La variable *self* es una instancia de la clase y no es ua palabra reservada de Python, cualquier etiqueta utilizada como primer parámetro tendría el mismo valor (no se aconseja usar otro valor por convención).  Cada vez que declaremos un método en Python, vamos a tener uqe agregarle la variable *self* para que cuando sea invocado el método, Python pase el objeto instanciado y opere con los valores actuales de esa instancia.  
  

In [87]:
# Definimos la clase con nombre Mascota
class Mascota:
  # Atributos
  especie = 'Gato'
  _oculto = 2

  
  def __init__(self,nombre,especie=especie):
    """
      El método __init__ es una función para inicializar la clase, si no se especifica la especie toma el valor por defecto definido en el atributo.
    """
    self.nombre = nombre
    self.especie = especie
    self._private=None
  
  def __str__(self):
    """
      El método __str__ es una función que proporciona una cadena informal de la representación del objeto.
    """
    return "%s es un %s" % (self.nombre, self.especie)

  def darNombre(self):
    """
      Retorna el nombre de la mascota.
    """
    return self.nombre
  
  def darEspecie(self):
    """
      Retorna la especie de la mascota.
    """
    return self.especie

In [88]:
Teo = Mascota("Teo","Perro")
print(Teo)

Teo es un Perro


In [89]:
Teo.especie='Gato'
print(Teo)

Teo es un Gato


# Funciones lambda

Lambdas es la forma de Python de definir funciones anónimas muy simples cuyo valor de retorno es el resultado de evaluar una sola expresión.

```python
lambda argumentos: resultado
```

Una de las razones por las que desees utilizar este tipo de funciones es por rapidez y en ciertos casos claridad del código.

In [90]:
# Define function
def function_sum(x,y):
  return x + y
function_sum(2,3)

5

In [91]:
# Define lambda
lambda_function = lambda x,y: x + y
lambda_function(2,3)

5

In [92]:
data_recs = [
  [ "Maria",  7.0, 8.0, 3.0 ],
  [ "Juan" ,  5.0, 2.0, 2.0 ],
  [ "Mateo",  1.0, 4.0, 4.0 ],     
]

In [93]:
data_recs[:][1][1]

5.0

In [94]:
sorted(data_recs)

[['Juan', 5.0, 2.0, 2.0], ['Maria', 7.0, 8.0, 3.0], ['Mateo', 1.0, 4.0, 4.0]]

In [95]:
records_sorted = sorted(data_recs, key = lambda rec : rec[1])
records_sorted

[['Mateo', 1.0, 4.0, 4.0], ['Juan', 5.0, 2.0, 2.0], ['Maria', 7.0, 8.0, 3.0]]

## Filtrando objetos

In [96]:
# Definimos una clase persona
class Persona:

    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def __str__(self):
        return "{} de {} años".format(self.nombre, self.edad)

# Se crea una lista con 4 personas
personas = [
    Persona("Juan", 35),
    Persona("Marta", 16),
    Persona("Manuel", 78),
    Persona("Eduardo", 12)
]

# Visualizamos la lista
for p in personas:
    print(p)

Juan de 35 años
Marta de 16 años
Manuel de 78 años
Eduardo de 12 años


In [97]:
# Se desea filtrar los menores de 18
menores = filter(lambda persona: persona.edad < 18, personas)

# Visualizamos los objetos de la lista filtrada
for menor in menores:
    print(menor)

Marta de 16 años
Eduardo de 12 años


## Ciclos y List Comprenhensions

Supongamos que nos dan: 

* Una lista de entrada input_arr = [elem1, elem2, elem3, ...]
* Una función fun

Queremos producir el array output_arr = [fun (elem1), fun (elem2), fun (elem3)], es decir, con aplicar fun a cada elemento de la matriz y devolver los resultados.

Aquí es cómo la mayoría de los programadores abordarían este problema:

In [98]:
input_arr = ["maria", "ana", "sara"]
capitalize = lambda a_str :  a_str[0].upper() + a_str[1:]

# NON-Idiomatic Python code follows: 
output_arr = []
for elem in input_arr : 
    output_arr.append( capitalize( elem ) )
    
output_arr

['Maria', 'Ana', 'Sara']

Eso es aproximadamente 3 líneas. No está mal, pero podría ser mucho mejor.
La solución idiomática de Python se llama **List (or for) comprehension**.

```python
[funcion(x) for item in list1]
```

In [99]:
output_arr2 = [ capitalize(elem)  for elem in input_arr ]
print(output_arr2)

['Maria', 'Ana', 'Sara']


## Condicionales en List Comprehensions

En este caso se desea realizar un condicional para definir el valor, se tienen dos estructuras, si la condición solo tiene IF, o si se tiene la estructura IF-ELSE

```python
[result1 if conditional else result2 for item in list1 ]
[result for item in list1 if conditional]
```

In [100]:
squares_cubes = [n**2 if n%2 == 0 else n**3 for n in range(1,16)]
print(squares_cubes)

[1, 4, 27, 16, 125, 36, 343, 64, 729, 100, 1331, 144, 2197, 196, 3375]


In [101]:
evens = [n for n in range(1,21) if n%2 == 0] 
print(evens)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [102]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]
 
transpose = [[row[n] for row in matrix] for n in range(4)]
 
print(transpose)

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]


## Ejercicio 5

Defina una función avg1 que tome una lista que conste del nombre de una persona (str) y luego solo números y calcula y devuelve el promedio de esos números.

Por ejemplo: 
```python
avg1 (['Mateo', 5.0, 2.0, 2.0])
``` 
debe devolver 3, es el resultado de realizar la siguiente operación: `((5 + 2 + 2) / 3))`

## Ejercicio 6

Use list-comprehension para aplicar la función avg1 definida anteriormente a cada registro en data_recs.

```python
data_recs = [
  [ "Juan" ,  5.0, 2.0, 2.0 ],
  [ "Maria",  7.0, 8.0, 3.0 ], 
  [ "Mateo",  1.0, 4.0, 4.0 ],     
]
````

## Archivos de texto y líneas
Un archivo de texto puede ser considerado como una secuencia de líneas, así como
una cadena de Python puede ser considerada como una secuencia de caracteres.
Por ejemplo, este es un ejemplo de un archivo de texto que registra la actividad
de correos de varias personas en un equipo de desarrollo de un proyecto de código
abierto (open source):

In [112]:
man_archivo = open('mbox-short.txt')
contador = 0
for linea in man_archivo:
    contador = contador + 1
print('Contador de líneas:', contador)


Contador de líneas: 1910


## Ejercicio 7

Escribir un programa para leer a través de datos de una bandeja de entrada de correo y
cuando encuentre una línea que comience con `From`, dividir la línea en palabras utilizando
la función split. Estamos interesados en quién envió el mensaje, lo cual es la segunda
palabra en las líneas que comienzan con From.
Por ejemplo se tienen lineas como la siguiente:

`From stephen.marquard@uct.ac.za Sat Jan 5 09:14:16 2008`

Se tienen que analizar la línea que empieza por From e imprimir la segunda palabra de cada
línea, siguiendo el ejemplo serìa imprimir `stephen.marquard@uct.ac.za` después tendrá
que contar el número de líneas (no incluir From:) e imprimir el total al final.


hint:se peude basar en las  funciones `.rstrip()  .split() `

### Numpy: manejo de arrays y matrices
Muchas de las funciones de la biblioteca numpy regresan el tipo de dato array, por
lo que en la página oficial (https://docs.scipy.org/doc/) la recomendación es que se realicen los
cálculos utilizando este tipo de datos. Mostramos con ejemplos el uso de algunas de
las funciones, adicionales a las que se presentaron en capítulos anteriores.


In [2]:
#Se importa la Biblioteca
import numpy as np
# Creamos una variable que contenga los valores del 0 al 9
a = np.arange(10)
# Desplegamos el valor de la variable
print(a)

[0 1 2 3 4 5 6 7 8 9]


Si una vez creado un arreglo deseamos conocer la forma (shape) y el tamaño (size)
del mismo, se puede hacer de la siguiente forma:


In [3]:
# Crear un arreglo multidimensional 2x2 con tipo de dato int32
A = np.array([[1, 2], [2, 4]] , np.int32)
print (A)


[[1 2]
 [2 4]]


In [4]:
print(A.shape)
# Para conocer el tamańo del arreglo
print(A.size)


(2, 2)
4


Existen también funciones que permiten crear matrices definidas y conocidas de álgebra lineal como la matriz identidad o matrices con ceros. La tabla  muestra de
manera condensada estas funciones.


<img src="operaciones basicas numpy.png" alt="" style="height:200px"></img>

In [7]:
I = np.eye(3)
b = np.zeros((3, 5))
o = np.ones((4, 6))
print(I)
print(b)
print(o)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


En la Tabla tenemos una lista de las operaciones elementales utilizadas para
manejar matrices. A lo largo del curso se hará uso de éstas y otras operaciones en
los diversos ejemplos.

<img src="matrices.png" alt="" style="height:200px"></img>

In [9]:
X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[7,8,9],[10,11,12]])
print(X+Y)
print(X-Y)
print(X*Y)
print(X/Y)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


## Ejercicio 8

cargar cualquier imagen a color, hallar las dimensiones , extraer y visualizar cada uno de sus canales de color(RGB), recortar la imagen en una region que considere de interes , en esa region hallar el promedio,la desviacion,  el maximo y el minimo   y realizar una operacion basica de matriz que exalte o mejore de alguna manera dicha region de inspeccion (suma , multiplicacion , resta(puede ser con otra imagen)), en fin ... deja fluir tu cratividad.

para la visualizacion se peude usar matplotlib y para la manipulacion de imagenes es recomendable usar numpy y/o OpenCV